language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "No installs"

# Scripts to be run such as tests
before_script:
  - echo "No tests"

script:
  - docker --version # print the version for logging

  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed kevintuei/udagram-api-feed:v5

  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user kevintuei/udagram-api-user:v5

  - docker build -t udagram-frontend ./udagram-api-feed
  - docker tag udagram-frontend kevintuei/udagram-frontend:v7

  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-reverseproxy kevintuei/udagram-reverseproxy:v8

  # - docker-compose
  # Tagging

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push kevintuei/udagram-api-feed:v5
  - docker push kevintuei/udagram-api-user:v5
  - docker push kevintuei/udagram-frontend:v7
  - docker push kevintuei/udagram-reverseproxy:v8    