apiVersion: v1
data:
  aws_access_key_id: QUtJQVdFSENLRkdDWTNITDRDSDY=
  aws_secret_access_key: NEpPVXlYQWJzMXpqU1JPNUhDR3cvc2lKNHQ4MDRUODlzd0hLYWV3Ug==
kind: Secret
metadata:
  creationTimestamp: null
  name: aws
type: string