apiVersion: v1
data:
  aws_access_key_id: QVNJQVdFSENLRkdDUU4yQ0xDR1E=
  aws_secret_access_key: OGFzdFVqV3Avb1F2MkdFOUR0dUc4VWxDVnVzZkNONFhDNUxwUXdNNA==
kind: Secret
metadata:
  creationTimestamp: null
  name: aws
type: string